name: example
description: A project that showcases how to enable the recommended lints for Catalyst Flutter apps, packages, and plugins.

publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dev_dependencies:
  catalyst_analysis:
    # When depending on this package from a real application you should use:
    # catalyst_analysis: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../